#!/usr/bin/env python3
'''
Automated test runner for variant enhanced_ai_variant_1_d7d6a9cc
Generated by Enhanced Agentic System
'''

import subprocess
import sys
import json
from pathlib import Path

def run_test(binary_path, test_case):
    try:
        result = subprocess.run(
            [binary_path] + test_case['input_args'],
            input=test_case['input_stdin'],
            capture_output=True,
            text=True,
            timeout=test_case['timeout']
        )
        
        # Check exit code
        if result.returncode != test_case['expected_exit_code']:
            return False, f"Exit code mismatch: expected {test_case['expected_exit_code']}, got {result.returncode}"
        
        # Check output (normalize whitespace and handle PID differences)
        expected = test_case['expected_output'].strip().replace('\r\n', '\n')
        actual = result.stdout.strip().replace('\r\n', '\n')
        
        # Handle Process ID differences (PIDs change between runs)
        import re
        expected_normalized = re.sub(r'Process ID: \d+', 'Process ID: [PID]', expected)
        actual_normalized = re.sub(r'Process ID: \d+', 'Process ID: [PID]', actual)
        
        if expected_normalized != actual_normalized:
            return False, f"Output mismatch:\nExpected: {repr(expected_normalized)}\nActual: {repr(actual_normalized)}"
        
        return True, "PASS"
        
    except subprocess.TimeoutExpired:
        return False, f"Test timed out after {test_case['timeout']} seconds"
    except Exception as e:
        return False, f"Test execution failed: {str(e)}"

def main():
    if len(sys.argv) != 2:
        print("Usage: python3 test_runner.py <binary_path>")
        sys.exit(1)
    
    binary_path = sys.argv[1]
    
    # Load test cases
    with open('test_cases.json', 'r') as f:
        test_cases = json.load(f)
    
    print(f"Running {len(test_cases)} test cases for {binary_path}")
    print("=" * 60)
    
    passed = 0
    failed = 0
    
    for i, test_case in enumerate(test_cases, 1):
        print(f"Test {i}: {test_case['name']}", end=" ... ")
        
        success, details = run_test(binary_path, test_case)
        
        if success:
            print("✅ PASS")
            passed += 1
        else:
            print("❌ FAIL")
            print(f"  {details}")
            failed += 1
    
    print("=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    print(f"Success rate: {passed/(passed+failed)*100:.1f}%")
    
    return failed == 0

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
